### ISSUE TITLE
Should `@cache-ttl` value be included in query identifier?

### ISSUE THREAD

**Issue by stockholmux** [gajus/slonik-interceptor-query-cache#1]
I'm to cache a query like this `SELECT * FROM teststuff`. I've abstracted the `get` and `set` method for my storage engine storage for slonik-interceptor-query-cache and the query is being processed (`JSON.stringify`) as shown in the dev.to article.

In one part of the application, I'm do this:

```
let foo = await connection.query(sql`-- @cache-ttl 30
     SELECT * FROM teststuff`);
```

and in another part of the application I'm do this:

```
let bar = await connection.query(sql`-- @cache-ttl 60
     SELECT * FROM teststuff`);
```

This results in two different cached responses, even though the query is the same. Should I be stripping the comment as the value should be the same. Should this be the responsibility of the cache interceptor?

**Comment by gajus** [comment]
I don't fully understand the question.

You have two separate queries and they have separate caches.

What is the reason you would expect them to share the cache if they are separate queries? (Not to mention with different TTLs)

**Comment by stockholmux** [comment]
The queries are only separate queries because they have been tagged with different `@cache-ttl` values. The underlying SQL is the same. Perhaps this is the intended, but if were doing this imperatively, I would just check the hashed SQL for a result in the cache, regardless of the TTL.

**Comment by gajus** [comment]
If TTLs are different, there is no guarantee that the results are going to be the same.
